### ISSUE TITLE
截图黏贴上传服务器报错

### ISSUE THREAD

**Issue by BreakerSAMA** [adlered/bolo-solo#121]
接入Picuang后，昨天还好好的
今天发文章贴图一闪而过，上传失败，换了本地的上传路径也一样
后台日志查看报错信息：

```
|> 10:11 09-03 org.b3log.solo.bolo.waf.WAFlogger:49 <| INFO << WAF [ACL] >> 10.255.0.2 >>> /pic/upload
java.io.FileNotFoundException: temp/image.png (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.commons.fileupload.disk.DiskFileItem.write(DiskFileItem.java:400)
	at org.b3log.solo.bolo.pic.PicUploadProcessor.uploadPicture(PicUploadProcessor.java:91)
	at org.b3log.solo.bolo.pic.PicUploadProcessor_$$_jvstcab_40._d10uploadPicture(PicUploadProcessor_$$_jvstcab_40.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.bolo.pic.PicUploadProcessor_$$_jvstcab_40.uploadPicture(PicUploadProcessor_$$_jvstcab_40.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:203)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:79)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:92)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:96)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by adlered** [comment]
问题已收到
