### ISSUE TITLE
🍍没有你喜欢的皮肤？

### ISSUE THREAD

**Issue by adlered** [adlered/bolo-solo#31]
Bolo 暂时移植了几款比较好看现代的皮肤，但也会有喜欢其它风格的朋友们。  
精力有限，照顾不周，皮肤太多，所以不知道大家喜欢什么皮肤。大家多多提出宝贵意见，每条皮肤的移植建议我都会看，移植速度也是一级的~  
↓ 如有想在 Bolo 用上的皮肤，写到评论中 :smile: ↓

**Comment by marklove5102** [comment]
皮肤坏了?
bolo-fantastic
500 Internal Server Error!

环境Windows 版本bolo_v1_7_stable_sp1   目前就这一个皮肤这样.

**Comment by adlered** [comment]
> 皮肤坏了?
> bolo-fantastic
> 500 Internal Server Error!
> 
> 环境Windows 版本bolo_v1_7_stable_sp1 目前就这一个皮肤这样.

抱歉为你带来困扰了~麻烦打开后台中的：`其他`-`日志浏览`，然后重新触发一下500，再将`日志浏览`中的全部日志回复给我，谢谢！

**Comment by marklove5102** [comment]
|> 16:04 04-21 org.b3log.solo.processor.KanBanNiangProcessor:116 <| INFO! Unpacking KanBanNiang resources...
|> 16:04 04-21 org.b3log.solo.processor.KanBanNiangProcessor:121 <| INFO! KanBanNiang is ready.
|> 16:04 04-21 org.b3log.latke.servlet.handler.BeforeHandleHandler:60 <| WARN! Occurred an exception before request processing: Unauthorized to request [/admin-index.do], please signin
|> 16:04 04-21 org.b3log.solo.processor.OAuthProcessor:142 <| INFO! Logged in [name=make, remoteAddr=127.0.0.1] with Bolo auth
|> 16:04 04-21 org.b3log.latke.servlet.renderer.AbstractFreeMarkerRenderer:131 <| ERROR! Renders template [index.ftl] failed [Request [
    method=GET,
    URL=http://127.0.0.1:8080/,
    contentType=null,
    characterEncoding=UTF-8,
    local=[
        addr=127.0.0.1,
        port=8080,
        name=127.0.0.1],
    remote=[
        addr=127.0.0.1,
        port=63888,
        host=127.0.0.1],
    headers=[
        Cookie=visited=%5B%22%2Ftags%2FBolo%22%2C%22%2F%22%5D; neverShowVer=v1.7%20%E7%A8%B3%E5%AE%9A%E7%89%88; skin=bolo-fantastic; mobile-skin=bolo-fantastic; solo=e39df312141343ec8b6cac715d97a981c9dca7c79d3e5e9e341c910fe1cff92dcac93637e1fec9aa3316f3bd65231e23cddf2d2338ac940dfe481d050f1a4b9f1ab1e50828d515df2ac08472c39a1cee
        Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Connection=keep-alive
        User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4115.0 Safari/537.36 Edg/84.0.488.0
        Sec-Fetch-Site=none
        Sec-Fetch-Dest=document
        Host=127.0.0.1:8080
        DNT=1
        Accept-Encoding=gzip, deflate, br
        Sec-Fetch-Mode=navigate
        Cache-Control=max-age=0
        Upgrade-Insecure-Requests=1
        Sec-Fetch-User=?1
        Accept-Language=zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
    ]
]]
FreeMarker template error:
An error has occurred when reading existing sub-variable "categoryURI"; see cause exception! The type of the containing value was: extended_hash+string (org.json.JSONObject wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #if article.categoryURI??  [in template "skins/bolo-fantastic/article-list.ftl" at line 80, column 37]
        - Reached through: #include "article-list.ftl"  [in template "skins/bolo-fantastic/index.ftl" at line 61, column 45]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
        at freemarker.ext.beans.BeanModel.get(BeanModel.java:183)
        at freemarker.core.Dot._eval(Dot.java:43)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.ExistsExpression._eval(ExistsExpression.java:49)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.Expression.evalToBoolean(Expression.java:179)
        at freemarker.core.Expression.evalToBoolean(Expression.java:165)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:373)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:337)
        at freemarker.core.Environment.include(Environment.java:2694)
        at freemarker.core.Include.accept(Include.java:171)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:337)
        at freemarker.core.Environment.process(Environment.java:310)
        at freemarker.template.Template.process(Template.java:383)
        at org.b3log.latke.servlet.renderer.AbstractFreeMarkerRenderer.genHTML(AbstractFreeMarkerRenderer.java:154)
        at org.b3log.solo.processor.SkinRenderer.genHTML(SkinRenderer.java:118)
        at org.b3log.latke.servlet.renderer.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:125)
        at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.java:118)
        at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:97)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:503)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
        at freemarker.ext.beans.BeanModel.invokeGenericGet(BeanModel.java:272)
        at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
        ... 60 more
Caused by: org.json.JSONException: JSONObject["categoryURI"] not found.
        at org.json.JSONObject.get(JSONObject.java:471)
        ... 67 more

**Comment by adlered** [comment]
这个应该是某个文章没有分类导致的。不过你那里不用修改，我这边改一下皮肤，稍后改好提醒你，到时提供给你一个单独的 article-list.ftl 文件，替换即可。感谢！麻烦加一下微信：1101635162

**Comment by marklove5102** [comment]
解决问题速度真快 哈哈.
